//! What a node needs before rows can move to it: the table's definition (columns, constraints,
//! indexes, row security, grants) and the login roles with the same SCRAM verifiers (L11). Read
//! from one node's catalog and replayed on another, never from a dump file.
//!
//! Foreign keys are not copied: a node checks only what it holds, so a key across nodes cannot
//! be one (L9), and `table distribute` refuses a table that has one it cannot keep.

use super::Kind;
use super::{OpError, Pg, qualified};
use crate::catalog::{Catalog, Keyspace, RelationKind, RelationName, quote_ident, quote_literal};
use crate::hash::KeyType;

pub async fn exists(pg: &mut Pg, rel: &RelationName) -> Result<bool, OpError> {
	Ok(pg
		.value("select to_regclass($1) is not null", &[&qualified(rel)])
		.await?
		.as_deref()
		== Some("t"))
}

pub async fn has_rows(pg: &mut Pg, rel: &RelationName) -> Result<bool, OpError> {
	Ok(pg
		.simple(&format!("select exists (select from {})", qualified(rel)))
		.await?
		.first()
		.and_then(|r| r.first().cloned().flatten())
		.as_deref()
		== Some("t"))
}

fn text(r: &[Option<String>], i: usize) -> String {
	r.get(i).cloned().flatten().unwrap_or_default()
}

/// The statements that make `rel` on another node, empty, as it is on `src`.
pub async fn ddl(src: &mut Pg, rel: &RelationName) -> Result<Vec<String>, OpError> {
	let name = qualified(rel);
	let t = name.as_str();
	let mut out = vec![format!(
		"create schema if not exists {}",
		quote_ident(&rel.schema)
	)];
	for r in src
		.query(
			"select coalesce(r.rolname, 'public'), a.privilege_type \
			from pg_namespace n cross join lateral aclexplode(n.nspacl) a \
			left join pg_roles r on r.oid = a.grantee \
			where n.nspname = $1 and a.grantee <> n.nspowner",
			&[&rel.schema],
		)
		.await?
	{
		out.push(format!(
			"grant {} on schema {} to {}",
			text(&r, 1),
			quote_ident(&rel.schema),
			grantee(&text(&r, 0))
		));
	}
	let columns = src
		.query(
			"select a.attname, format_type(a.atttypid, a.atttypmod), a.attnotnull, \
			pg_get_expr(d.adbin, d.adrelid), a.attidentity, a.attgenerated, \
			case when a.attcollation <> 0 and a.attcollation <> ty.typcollation then \
				(select quote_ident(cn.nspname) || '.' || quote_ident(co.collname) \
				from pg_collation co join pg_namespace cn on cn.oid = co.collnamespace \
				where co.oid = a.attcollation) end \
			from pg_attribute a \
			join pg_type ty on ty.oid = a.atttypid \
			left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum \
			where a.attrelid = $1::regclass and a.attnum > 0 and not a.attisdropped \
			order by a.attnum",
			&[t],
		)
		.await?;
	if columns.is_empty() {
		return Err(OpError::refused(
			Kind::NoSuchTable,
			format!("{rel} has no columns, or does not exist"),
		));
	}
	let cols: Vec<String> = columns
		.iter()
		.map(|r| {
			let mut c = format!("{} {}", quote_ident(&text(r, 0)), text(r, 1));
			let collation = text(r, 6);
			if !collation.is_empty() {
				c.push_str(&format!(" collate {collation}"));
			}
			let default = text(r, 3);
			match (text(r, 4).as_str(), text(r, 5).as_str()) {
				("a", _) => c.push_str(" generated always as identity"),
				("d", _) => c.push_str(" generated by default as identity"),
				(_, "s") => c.push_str(&format!(" generated always as ({default}) stored")),
				_ if !default.is_empty() => c.push_str(&format!(" default {default}")),
				_ => {}
			}
			if text(r, 2) == "t" {
				c.push_str(" not null");
			}
			c
		})
		.collect();
	out.push(format!("create table {t} ({})", cols.join(", ")));
	for r in src
		.query(
			"select conname, pg_get_constraintdef(oid) from pg_constraint \
			where conrelid = $1::regclass and contype in ('p', 'u', 'c', 'x') \
			and conname <> 'lepis_owns' order by contype <> 'p', conname",
			&[t],
		)
		.await?
	{
		out.push(format!(
			"alter table {t} add constraint {} {}",
			quote_ident(&text(&r, 0)),
			text(&r, 1)
		));
	}
	for r in src
		.query(
			"select pg_get_indexdef(i.indexrelid) from pg_index i where i.indrelid = $1::regclass \
			and not exists (select from pg_constraint c where c.conindid = i.indexrelid \
			and c.conrelid = i.indrelid)",
			&[t],
		)
		.await?
	{
		out.push(text(&r, 0));
	}
	let rls = src
		.query(
			"select relrowsecurity, relforcerowsecurity, pg_get_userbyid(relowner) \
			from pg_class where oid = $1::regclass",
			&[t],
		)
		.await?;
	if let Some(r) = rls.first() {
		out.push(format!(
			"alter table {t} owner to {}",
			quote_ident(&text(r, 2))
		));
		if text(r, 0) == "t" {
			out.push(format!("alter table {t} enable row level security"));
		}
		if text(r, 1) == "t" {
			out.push(format!("alter table {t} force row level security"));
		}
	}
	for r in src
		.query(
			"select policyname, permissive, cmd, \
			array_to_string(array(select case when x = 'public' then 'public' else quote_ident(x) end \
				from unnest(roles) x), ', '), qual, with_check \
			from pg_policies where schemaname = $1 and tablename = $2",
			&[&rel.schema, &rel.table],
		)
		.await?
	{
		let mut p = format!(
			"create policy {} on {t} as {} for {} to {}",
			quote_ident(&text(&r, 0)),
			text(&r, 1).to_lowercase(),
			text(&r, 2).to_lowercase(),
			text(&r, 3)
		);
		if !text(&r, 4).is_empty() {
			p.push_str(&format!(" using ({})", text(&r, 4)));
		}
		if !text(&r, 5).is_empty() {
			p.push_str(&format!(" with check ({})", text(&r, 5)));
		}
		out.push(p);
	}
	for r in src
		.query(
			"select coalesce(r.rolname, 'public'), a.privilege_type \
			from pg_class c cross join lateral aclexplode(c.relacl) a \
			left join pg_roles r on r.oid = a.grantee \
			where c.oid = $1::regclass and a.grantee <> c.relowner",
			&[t],
		)
		.await?
	{
		out.push(format!(
			"grant {} on {t} to {}",
			text(&r, 1),
			grantee(&text(&r, 0))
		));
	}
	Ok(out)
}

fn grantee(r: &str) -> String {
	if r == "public" {
		"public".into()
	} else {
		quote_ident(r)
	}
}

/// Makes `rel` on `dst` from `src`'s definition if `dst` does not have it. Returns whether it
/// was made.
pub async fn ensure_table(src: &mut Pg, dst: &mut Pg, rel: &RelationName) -> Result<bool, OpError> {
	if exists(dst, rel).await? {
		return Ok(false);
	}
	let statements = ddl(src, rel).await?;
	let mut sql = String::from("begin;\n");
	for s in statements {
		sql.push_str(&s);
		sql.push_str(";\n");
	}
	sql.push_str("commit;");
	if let Err(e) = dst.simple(&sql).await {
		let _ = dst.simple("rollback").await;
		return Err(e);
	}
	Ok(true)
}

/// Whether rows of `rel` can move by logical replication, and (with a key) whether it may be
/// sharded by `key` in `ks` (L15): every primary key and unique constraint includes the key, the
/// key's type is the keyspace's, no sequence fills a column, and no foreign key reaches a table
/// on another node.
pub async fn check_movable(
	pg: &mut Pg,
	rel: &RelationName,
	shard: Option<(&str, &Keyspace)>,
	catalog: &Catalog,
) -> Result<(), OpError> {
	let t = qualified(rel);
	if !exists(pg, rel).await? {
		return Err(OpError::refused(
			Kind::NoSuchTable,
			format!("{rel} does not exist on {}", pg.label),
		));
	}
	let ident = pg
		.query(
			"select relreplident, exists (select from pg_index where indrelid = c.oid and indisprimary) \
			from pg_class c where oid = $1::regclass",
			&[&t],
		)
		.await?;
	let ident = ident.first().cloned().unwrap_or_default();
	match (text(&ident, 0).as_str(), text(&ident, 1).as_str()) {
		("n", _) | ("d", "f") => {
			return Err(OpError::refused(
				Kind::TableNotMovable,
				format!(
					"{rel} has no primary key: a move replays its updates and deletes by key; add one, or set REPLICA IDENTITY FULL"
				),
			));
		}
		_ => {}
	}
	let Some((key, ks)) = shard else {
		return Ok(());
	};
	let ty = pg
		.value(
			"select format_type(atttypid, atttypmod) from pg_attribute \
			where attrelid = $1::regclass and attname = $2 and not attisdropped",
			&[&t, key],
		)
		.await?
		.ok_or_else(|| {
			OpError::refused(Kind::NoSuchColumn, format!("{rel} has no column {key}"))
		})?;
	let base = ty.split('(').next().unwrap_or_default().trim().to_string();
	if KeyType::from_sql_name(&base) != Some(ks.key_type) {
		return Err(OpError::refused(
			Kind::TableNotShardable,
			format!(
				"{rel}.{key} is {ty}, and keyspace {} is keyed by {}",
				ks.name,
				ks.key_type.sql_name()
			),
		));
	}
	let missing = pg
		.query(
			"select conname from pg_constraint c where conrelid = $1::regclass \
			and contype in ('p', 'u') and not exists (select from unnest(c.conkey) k \
			join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k where a.attname = $2)",
			&[&t, key],
		)
		.await?;
	if let Some(r) = missing.first() {
		return Err(OpError::refused(
			Kind::TableNotShardable,
			format!(
				"constraint {} on {rel} does not include the shard key {key}: a node can only check uniqueness over what it holds (L15)",
				text(r, 0)
			),
		));
	}
	let sequences = pg
		.query(
			"select a.attname from pg_attribute a left join pg_attrdef d \
			on d.adrelid = a.attrelid and d.adnum = a.attnum \
			where a.attrelid = $1::regclass and a.attnum > 0 and not a.attisdropped \
			and (a.attidentity <> '' or pg_get_expr(d.adbin, d.adrelid) like 'nextval(%')",
			&[&t],
		)
		.await?;
	if let Some(r) = sequences.first() {
		return Err(OpError::refused(
			Kind::TableNotShardable,
			format!(
				"{rel}.{} is filled by a sequence, which is not global across nodes (L15): use uuidv7(), or a per-node sequence striped by node",
				text(r, 0)
			),
		));
	}
	let fks = pg
		.query(
			"select c.conname, rn.nspname, r.relname, fn.nspname, f.relname \
			from pg_constraint c \
			join pg_class r on r.oid = c.conrelid join pg_namespace rn on rn.oid = r.relnamespace \
			join pg_class f on f.oid = c.confrelid join pg_namespace fn on fn.oid = f.relnamespace \
			where c.contype = 'f' and (c.conrelid = $1::regclass or c.confrelid = $1::regclass)",
			&[&t],
		)
		.await?;
	for r in fks {
		let from = RelationName {
			schema: text(&r, 1),
			table: text(&r, 2),
		};
		let to = RelationName {
			schema: text(&r, 3),
			table: text(&r, 4),
		};
		let other = if &from == rel { &to } else { &from };
		if other == rel {
			continue;
		}
		let ok = match catalog.relations.get(other) {
			Some(RelationKind::Sharded { keyspace, .. }) => keyspace == &ks.name,
			Some(RelationKind::Reference) => &from == rel,
			_ => false,
		};
		if !ok {
			return Err(OpError::refused(
				Kind::TableNotShardable,
				format!(
					"foreign key {} links {rel} to {other}, which will not be on the same node: colocate {other} in keyspace {}, make it a reference table, or drop the key (L9)",
					text(&r, 0),
					ks.name
				),
			));
		}
	}
	Ok(())
}

/// The home node's login roles on `dst`, with the same verifiers and memberships (L11). Roles
/// are created or altered, never dropped. Superusers and roles with REPLICATION are left alone.
pub async fn sync_roles(home: &mut Pg, dst: &mut Pg) -> Result<usize, OpError> {
	let roles = home
		.query(
			"select rolname, rolpassword, rolcanlogin, rolinherit, rolcreatedb, rolcreaterole, \
			rolconnlimit, rolvaliduntil::text from pg_authid \
			where rolname !~ '^pg_' and not rolsuper and not rolreplication and oid >= 16384 \
			order by rolname",
			&[],
		)
		.await?;
	let mut sql = String::from("begin;\n");
	for r in &roles {
		let name = text(r, 0);
		let flag = |i: usize, yes: &str, no: &str| {
			if text(r, i) == "t" {
				yes.to_string()
			} else {
				no.to_string()
			}
		};
		sql.push_str(&format!(
			"do $$ begin if not exists (select from pg_roles where rolname = {}) then create role {}; end if; end $$;\n",
			quote_literal(&name),
			quote_ident(&name)
		));
		let password = r
			.get(1)
			.cloned()
			.flatten()
			.map_or("null".to_string(), |p| quote_literal(&p));
		let until = r
			.get(7)
			.cloned()
			.flatten()
			.map_or("'infinity'".to_string(), |p| quote_literal(&p));
		sql.push_str(&format!(
			"alter role {} {} {} {} {} connection limit {} password {password} valid until {until};\n",
			quote_ident(&name),
			flag(2, "login", "nologin"),
			flag(3, "inherit", "noinherit"),
			flag(4, "createdb", "nocreatedb"),
			flag(5, "createrole", "nocreaterole"),
			text(r, 6),
		));
	}
	for r in home
		.query(
			"select r.rolname, m.rolname from pg_auth_members a \
			join pg_roles r on r.oid = a.roleid join pg_roles m on m.oid = a.member \
			where r.rolname !~ '^pg_' and m.rolname !~ '^pg_' and not m.rolsuper and not r.rolsuper",
			&[],
		)
		.await?
	{
		sql.push_str(&format!(
			"grant {} to {};\n",
			quote_ident(&text(&r, 0)),
			quote_ident(&text(&r, 1))
		));
	}
	sql.push_str("commit;");
	if let Err(e) = dst.simple(&sql).await {
		let _ = dst.simple("rollback").await;
		return Err(e);
	}
	Ok(roles.len())
}
